/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controle.ControladorCadastroEmpresa;
import entidade.Empresa;
import javax.swing.JOptionPane;

/**
 *
 * @author edmar
 */
public class JanelaCadastroEmpresas extends javax.swing.JFrame {
    private ControladorCadastroEmpresa controlador;
    /**
     * Creates new form JanelaCadastroEmpresa
     */
    public JanelaCadastroEmpresas() {
        initComponents();
        this.controlador = new ControladorCadastroEmpresa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idEmpresaLabel = new javax.swing.JLabel();
        cnpjEmpresaLabel = new javax.swing.JLabel();
        cnpjEmpresaTextField = new javax.swing.JTextField();
        idEmpresaTextField = new javax.swing.JTextField();
        cadastrarEmpresaButton = new javax.swing.JButton();
        removerEmpresaButton = new javax.swing.JButton();
        atualizarEmpresaButton = new javax.swing.JButton();
        nomeEmpresaLabel = new javax.swing.JLabel();
        nomeEmpresaTextField = new javax.swing.JTextField();
        enderecoEmpresaLabel = new javax.swing.JLabel();
        buscarEmpresaButton = new javax.swing.JButton();
        limparCamposEmpresaButton = new javax.swing.JButton();
        enderecoEmpresaTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idEmpresaLabel.setText("ID");

        cnpjEmpresaLabel.setText("CNPJ");

        cnpjEmpresaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjEmpresaTextFieldActionPerformed(evt);
            }
        });

        idEmpresaTextField.setEditable(false);
        idEmpresaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEmpresaTextFieldActionPerformed(evt);
            }
        });

        cadastrarEmpresaButton.setText("Cadastrar");
        cadastrarEmpresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEmpresaButtonActionPerformed(evt);
            }
        });

        removerEmpresaButton.setText("Remover");
        removerEmpresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerEmpresaButtonActionPerformed(evt);
            }
        });

        atualizarEmpresaButton.setText("Atualizar");
        atualizarEmpresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarEmpresaButtonActionPerformed(evt);
            }
        });

        nomeEmpresaLabel.setText("Nome");

        nomeEmpresaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEmpresaTextFieldActionPerformed(evt);
            }
        });

        enderecoEmpresaLabel.setText("Endereço");

        buscarEmpresaButton.setText("Buscar");
        buscarEmpresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEmpresaButtonActionPerformed(evt);
            }
        });

        limparCamposEmpresaButton.setText("Limpar Campos");

        enderecoEmpresaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoEmpresaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nomeEmpresaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nomeEmpresaTextField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cadastrarEmpresaButton)
                            .addGap(44, 44, 44)
                            .addComponent(atualizarEmpresaButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removerEmpresaButton)
                            .addGap(41, 41, 41)
                            .addComponent(buscarEmpresaButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(323, 323, 323)
                            .addComponent(limparCamposEmpresaButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cnpjEmpresaLabel)
                                .addComponent(idEmpresaLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idEmpresaTextField)
                                .addComponent(cnpjEmpresaTextField))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enderecoEmpresaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enderecoEmpresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEmpresaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idEmpresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpjEmpresaLabel)
                    .addComponent(cnpjEmpresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEmpresaLabel)
                    .addComponent(nomeEmpresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoEmpresaLabel)
                    .addComponent(enderecoEmpresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarEmpresaButton)
                    .addComponent(atualizarEmpresaButton)
                    .addComponent(removerEmpresaButton)
                    .addComponent(buscarEmpresaButton))
                .addGap(32, 32, 32)
                .addComponent(limparCamposEmpresaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idEmpresaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEmpresaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEmpresaTextFieldActionPerformed

    private void cnpjEmpresaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjEmpresaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjEmpresaTextFieldActionPerformed

    private void nomeEmpresaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEmpresaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEmpresaTextFieldActionPerformed

    private void cadastrarEmpresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEmpresaButtonActionPerformed
        String cnpj = cnpjEmpresaTextField.getText();
        String nome = nomeEmpresaTextField.getText();
        String endereco = enderecoEmpresaTextField.getText();
        if(controlador.verificarCnpjExistente(cnpj)){
            JOptionPane.showMessageDialog(null, "CNPJ já cadastrado!", "Alerta", JOptionPane.WARNING_MESSAGE);
            return;
        }
        controlador.adicionarEmpresa(cnpj, nome, endereco);
        JOptionPane.showMessageDialog(this, "Empresa cadastrada com sucesso!");

        this.limparTextos();
    }//GEN-LAST:event_cadastrarEmpresaButtonActionPerformed

    private void removerEmpresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerEmpresaButtonActionPerformed
        String idText = idEmpresaTextField.getText();
        int id = Integer.parseInt(idText);

        controlador.removerEmpresa(id);

        JOptionPane.showMessageDialog(this, "Empresa removida com sucesso!");

        this.limparTextos();
    }//GEN-LAST:event_removerEmpresaButtonActionPerformed

    private void enderecoEmpresaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoEmpresaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoEmpresaTextFieldActionPerformed

    private void atualizarEmpresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarEmpresaButtonActionPerformed
        int id = Integer.parseInt(idEmpresaTextField.getText());
        String cnpj = cnpjEmpresaTextField.getText();
        String nome = nomeEmpresaTextField.getText();
        String endereço = enderecoEmpresaTextField.getText();

        controlador.atualizarEmpresa(id, cnpj, nome, endereço);
        
        JOptionPane.showMessageDialog(this, "Empresa atualizada com sucesso!");
    }//GEN-LAST:event_atualizarEmpresaButtonActionPerformed

    private void buscarEmpresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEmpresaButtonActionPerformed
        String cnpj = cnpjEmpresaTextField.getText();
        Empresa empresa = controlador.buscarEmpresaPorCNPJ(cnpj);

        // Exibir informações do empregado encontrado (por exemplo, preencher campos de texto)
        if (empresa != null) {
            cnpjEmpresaTextField.setText(String.valueOf(empresa.getCNPJ()));
            idEmpresaTextField.setText(String.valueOf(empresa.getId()));
            nomeEmpresaTextField.setText(empresa.getNome());
            enderecoEmpresaTextField.setText(empresa.getEndereco());
        } else {
            JOptionPane.showMessageDialog(null, "Não encontrado nenhuma empresa com esse nome!", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buscarEmpresaButtonActionPerformed
    
    private void limparTextos(){
        idEmpresaTextField.setText("");
        cnpjEmpresaTextField.setText("");
        nomeEmpresaTextField.setText("");
        enderecoEmpresaTextField.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastroEmpresas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarEmpresaButton;
    private javax.swing.JButton buscarEmpresaButton;
    private javax.swing.JButton cadastrarEmpresaButton;
    private javax.swing.JLabel cnpjEmpresaLabel;
    private javax.swing.JTextField cnpjEmpresaTextField;
    private javax.swing.JLabel enderecoEmpresaLabel;
    private javax.swing.JTextField enderecoEmpresaTextField;
    private javax.swing.JLabel idEmpresaLabel;
    private javax.swing.JTextField idEmpresaTextField;
    private javax.swing.JButton limparCamposEmpresaButton;
    private javax.swing.JLabel nomeEmpresaLabel;
    private javax.swing.JTextField nomeEmpresaTextField;
    private javax.swing.JButton removerEmpresaButton;
    // End of variables declaration//GEN-END:variables
}
