/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;
import controle.ControladorCadastroEmpregado;
import entidade.Empregado;
import javax.swing.JOptionPane;

/**
 *
 * @author edmar
 */
public class JanelaCadastroEmpregados extends javax.swing.JFrame {
    private ControladorCadastroEmpregado controlador;

    /**
     * Creates new form JanelaRecursosHumanos
     */
    public JanelaCadastroEmpregados() {
        initComponents();
        controlador = new ControladorCadastroEmpregado();
    }

    public JanelaCadastroEmpregados(ControladorCadastroEmpregado aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeEmpregadoLabel = new javax.swing.JLabel();
        cargoEmpregadoLabel = new javax.swing.JLabel();
        salarioEmpregadoLabel = new javax.swing.JLabel();
        nomeEmpregadoTextField = new javax.swing.JTextField();
        cargoEmpregadoTextField = new javax.swing.JTextField();
        salarioEmpregadoTextField = new javax.swing.JTextField();
        cadastrarEmpregadoButton = new javax.swing.JButton();
        atualizarEmpregadoButton = new javax.swing.JButton();
        limparCamposButton = new javax.swing.JButton();
        idEmpregadoLabel = new javax.swing.JLabel();
        idEmpregadoTextField = new javax.swing.JTextField();
        removerEmpregadoButton = new javax.swing.JButton();
        buscarEmpregadoButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recursos Humanos");

        nomeEmpregadoLabel.setText("Nome:");

        cargoEmpregadoLabel.setText("Cargo:");

        salarioEmpregadoLabel.setText("Salário:");

        nomeEmpregadoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEmpregadoTextFieldActionPerformed(evt);
            }
        });

        cargoEmpregadoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoEmpregadoTextFieldActionPerformed(evt);
            }
        });

        salarioEmpregadoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioEmpregadoTextFieldActionPerformed(evt);
            }
        });

        cadastrarEmpregadoButton.setText("Adicionar");
        cadastrarEmpregadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEmpregadoButtonActionPerformed(evt);
            }
        });

        atualizarEmpregadoButton.setText("Atualizar");
        atualizarEmpregadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarEmpregadoButtonActionPerformed(evt);
            }
        });

        limparCamposButton.setText("Limpar Campos");
        limparCamposButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCamposButtonActionPerformed(evt);
            }
        });

        idEmpregadoLabel.setText("ID:");

        idEmpregadoTextField.setEditable(false);
        idEmpregadoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEmpregadoTextFieldActionPerformed(evt);
            }
        });

        removerEmpregadoButton.setText("Remover");
        removerEmpregadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerEmpregadoButtonActionPerformed(evt);
            }
        });

        buscarEmpregadoButton.setText("Buscar");
        buscarEmpregadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEmpregadoButtonActionPerformed(evt);
            }
        });

        jMenu2.setText("Empregados");
        jMenu2.add(jSeparator1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(salarioEmpregadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(cargoEmpregadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomeEmpregadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idEmpregadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeEmpregadoTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cargoEmpregadoTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(salarioEmpregadoTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idEmpregadoTextField))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrarEmpregadoButton)
                        .addGap(18, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(limparCamposButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buscarEmpregadoButton)
                                .addGap(29, 29, 29)
                                .addComponent(atualizarEmpregadoButton)
                                .addGap(28, 28, 28)
                                .addComponent(removerEmpregadoButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEmpregadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idEmpregadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEmpregadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeEmpregadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargoEmpregadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoEmpregadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salarioEmpregadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioEmpregadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrarEmpregadoButton)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(removerEmpregadoButton)
                        .addComponent(atualizarEmpregadoButton)
                        .addComponent(buscarEmpregadoButton)))
                .addGap(18, 18, 18)
                .addComponent(limparCamposButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeEmpregadoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEmpregadoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEmpregadoTextFieldActionPerformed

    private void cargoEmpregadoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoEmpregadoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoEmpregadoTextFieldActionPerformed

    private void salarioEmpregadoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioEmpregadoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioEmpregadoTextFieldActionPerformed

    private void cadastrarEmpregadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEmpregadoButtonActionPerformed
        String nome = nomeEmpregadoTextField.getText();
        String cargo = cargoEmpregadoTextField.getText();
        double salario = Double.parseDouble(salarioEmpregadoTextField.getText());;
        controlador.adicionarEmpregado(nome, cargo, salario);
        JOptionPane.showMessageDialog(this, "Empregado cadastrado com sucesso!");
        this.limparTextos();
    }//GEN-LAST:event_cadastrarEmpregadoButtonActionPerformed
 
    private void atualizarEmpregadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarEmpregadoButtonActionPerformed
        int id = Integer.parseInt(idEmpregadoTextField.getText());
        String nome = nomeEmpregadoTextField.getText();
        String cargo = cargoEmpregadoTextField.getText();
        double salario = Double.parseDouble(salarioEmpregadoTextField.getText());

        controlador.atualizarEmpregado(id, nome, cargo, salario);
        
        JOptionPane.showMessageDialog(this, "Empregado atualizado com sucesso!");
    }//GEN-LAST:event_atualizarEmpregadoButtonActionPerformed

    private void limparCamposButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCamposButtonActionPerformed
        idEmpregadoTextField.setText("");
        nomeEmpregadoTextField.setText("");
        cargoEmpregadoTextField.setText("");
        salarioEmpregadoTextField.setText("");
    }//GEN-LAST:event_limparCamposButtonActionPerformed

    private void idEmpregadoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEmpregadoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEmpregadoTextFieldActionPerformed

    private void removerEmpregadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerEmpregadoButtonActionPerformed
        // TODO add your handling code here:
        String idText = idEmpregadoTextField.getText();
        int id = Integer.parseInt(idText);

        controlador.removerEmpregado(id);

        JOptionPane.showMessageDialog(this, "Empregado removido com sucesso!");

        this.limparTextos();
    }//GEN-LAST:event_removerEmpregadoButtonActionPerformed

    private void buscarEmpregadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEmpregadoButtonActionPerformed
        String nome = nomeEmpregadoTextField.getText();
        Empregado empregado = controlador.buscarEmpregadoPorNome(nome);

        // Exibir informações do empregado encontrado (por exemplo, preencher campos de texto)
        if (empregado != null) {
            idEmpregadoTextField.setText(String.valueOf(empregado.getId()));
            nomeEmpregadoTextField.setText(empregado.getNome());
            cargoEmpregadoTextField.setText(empregado.getCargo());
            salarioEmpregadoTextField.setText(String.valueOf(empregado.getSalário()));
        } else {
            JOptionPane.showMessageDialog(null, "Não encontrado nenhum empregado com esse nome!", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buscarEmpregadoButtonActionPerformed
    
    
    private void limparTextos(){
        idEmpregadoTextField.setText("");
        nomeEmpregadoTextField.setText("");
        cargoEmpregadoTextField.setText("");
        salarioEmpregadoTextField.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroEmpregados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroEmpregados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroEmpregados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroEmpregados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastroEmpregados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarEmpregadoButton;
    private javax.swing.JButton buscarEmpregadoButton;
    private javax.swing.JButton cadastrarEmpregadoButton;
    private javax.swing.JLabel cargoEmpregadoLabel;
    private javax.swing.JTextField cargoEmpregadoTextField;
    private javax.swing.JLabel idEmpregadoLabel;
    private javax.swing.JTextField idEmpregadoTextField;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton limparCamposButton;
    private javax.swing.JLabel nomeEmpregadoLabel;
    private javax.swing.JTextField nomeEmpregadoTextField;
    private javax.swing.JButton removerEmpregadoButton;
    private javax.swing.JLabel salarioEmpregadoLabel;
    private javax.swing.JTextField salarioEmpregadoTextField;
    // End of variables declaration//GEN-END:variables
}
