/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;
import controle.ControladorCadastroEmpresa;
import entidade.Empresa;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author edmar
 */
public class JanelaCadastroEmpresas extends javax.swing.JFrame {
    private ControladorCadastroEmpresa controlador;

    /**
     * Creates new form JanelaCadastroEmpresas
     */
    public JanelaCadastroEmpresas() {
        this.controlador = new ControladorCadastroEmpresa();
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.inicializarComboBoxEmpresa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empresasCadastradasLabel = new javax.swing.JLabel();
        idEmpresaLabel = new javax.swing.JLabel();
        idEmpresaTextField = new javax.swing.JTextField();
        nomeEmpresaLabel = new javax.swing.JLabel();
        nomeEmpresaTextField = new javax.swing.JTextField();
        cnpjEmpresaTextField = new javax.swing.JTextField();
        cnpjEmpresaLabel = new javax.swing.JLabel();
        enderecoEmpresaLabel = new javax.swing.JLabel();
        enderecoEmpresaTextField = new javax.swing.JTextField();
        cadastrarEmpresaButton = new javax.swing.JButton();
        atualizarEmpresaButton = new javax.swing.JButton();
        removerEmpresaButton = new javax.swing.JButton();
        buscarEmpresaButton = new javax.swing.JButton();
        limparCamposEmpresaButton = new javax.swing.JButton();
        empresasCadastradasComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Empresas");

        empresasCadastradasLabel.setText("Empresas Cadastradas");

        idEmpresaLabel.setText("ID");

        idEmpresaTextField.setEditable(false);
        idEmpresaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEmpresaTextFieldActionPerformed(evt);
            }
        });

        nomeEmpresaLabel.setText("Nome");

        nomeEmpresaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEmpresaTextFieldActionPerformed(evt);
            }
        });

        cnpjEmpresaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjEmpresaTextFieldActionPerformed(evt);
            }
        });

        cnpjEmpresaLabel.setText("CNPJ");

        enderecoEmpresaLabel.setText("Endereço");

        enderecoEmpresaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoEmpresaTextFieldActionPerformed(evt);
            }
        });

        cadastrarEmpresaButton.setText("Cadastrar");
        cadastrarEmpresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEmpresaButtonActionPerformed(evt);
            }
        });

        atualizarEmpresaButton.setText("Alterar");
        atualizarEmpresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarEmpresaButtonActionPerformed(evt);
            }
        });

        removerEmpresaButton.setText("Remover");
        removerEmpresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerEmpresaButtonActionPerformed(evt);
            }
        });

        buscarEmpresaButton.setText("Buscar");
        buscarEmpresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEmpresaButtonActionPerformed(evt);
            }
        });

        limparCamposEmpresaButton.setText("Limpar Campos");
        limparCamposEmpresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCamposEmpresaButtonActionPerformed(evt);
            }
        });

        empresasCadastradasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        empresasCadastradasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresasCadastradasComboBoxActionPerformed(evt);
            }
        });
        empresasCadastradasComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                empresasCadastradasComboBoxPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrarEmpresaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atualizarEmpresaButton)
                        .addGap(43, 43, 43)
                        .addComponent(removerEmpresaButton)
                        .addGap(30, 30, 30)
                        .addComponent(buscarEmpresaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(empresasCadastradasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(empresasCadastradasComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeEmpresaLabel)
                            .addComponent(idEmpresaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idEmpresaTextField)
                            .addComponent(nomeEmpresaTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(limparCamposEmpresaButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnpjEmpresaLabel)
                            .addComponent(enderecoEmpresaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoEmpresaTextField)
                            .addComponent(cnpjEmpresaTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empresasCadastradasLabel)
                    .addComponent(empresasCadastradasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEmpresaLabel)
                    .addComponent(idEmpresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEmpresaLabel)
                    .addComponent(nomeEmpresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpjEmpresaLabel)
                    .addComponent(cnpjEmpresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoEmpresaLabel)
                    .addComponent(enderecoEmpresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarEmpresaButton)
                    .addComponent(atualizarEmpresaButton)
                    .addComponent(removerEmpresaButton)
                    .addComponent(buscarEmpresaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(limparCamposEmpresaButton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idEmpresaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEmpresaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEmpresaTextFieldActionPerformed

    private void nomeEmpresaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEmpresaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEmpresaTextFieldActionPerformed

    private void cnpjEmpresaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjEmpresaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjEmpresaTextFieldActionPerformed

    private void enderecoEmpresaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoEmpresaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoEmpresaTextFieldActionPerformed

    private void cadastrarEmpresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEmpresaButtonActionPerformed
        String cnpj = cnpjEmpresaTextField.getText();
        String nome = nomeEmpresaTextField.getText().replace("-", "");
        String endereco = enderecoEmpresaTextField.getText();
        if(controlador.verificarCnpjExistente(cnpj)){
            JOptionPane.showMessageDialog(null, "CNPJ já cadastrado!", "Alerta", JOptionPane.WARNING_MESSAGE);
            return;
        }
        controlador.adicionarEmpresa(cnpj, nome, endereco);
        this.inicializarComboBoxEmpresa();
        this.limparTextos();
    }//GEN-LAST:event_cadastrarEmpresaButtonActionPerformed

    private void atualizarEmpresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarEmpresaButtonActionPerformed
        int id = Integer.parseInt(idEmpresaTextField.getText());
        String cnpj = cnpjEmpresaTextField.getText();
        String nome = nomeEmpresaTextField.getText().replace("-", "");
        String endereço = enderecoEmpresaTextField.getText();
        String nomeECNPJ = (String) empresasCadastradasComboBox.getSelectedItem();
        controlador.atualizarEmpresa(id, cnpj, nome, endereço);
        this.inicializarComboBoxEmpresa();
        this.limparTextos();
    }//GEN-LAST:event_atualizarEmpresaButtonActionPerformed

    private void removerEmpresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerEmpresaButtonActionPerformed
        String idText = idEmpresaTextField.getText();
        int id = Integer.parseInt(idText);

        controlador.removerEmpresa(id);
        this.inicializarComboBoxEmpresa();
        this.limparTextos();
    }//GEN-LAST:event_removerEmpresaButtonActionPerformed

    private void buscarEmpresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEmpresaButtonActionPerformed
        String cnpj = cnpjEmpresaTextField.getText();
        Empresa empresa = controlador.buscarEmpresaPorCNPJ(cnpj);

        // Exibir informações do empregado encontrado (por exemplo, preencher campos de texto)
        if (empresa != null) {
            this.preencherCampos(empresa);
        } else {
            JOptionPane.showMessageDialog(null, "Não encontrado nenhuma empresa com esse CNPJ!", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buscarEmpresaButtonActionPerformed

    private void limparCamposEmpresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCamposEmpresaButtonActionPerformed
        this.limparTextos();
    }//GEN-LAST:event_limparCamposEmpresaButtonActionPerformed

    private void empresasCadastradasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresasCadastradasComboBoxActionPerformed
        // TODO add your handling code here:
        String empresaSelecionada = (String) empresasCadastradasComboBox.getSelectedItem();
        this.selecionarEmpresa(empresaSelecionada);
    }//GEN-LAST:event_empresasCadastradasComboBoxActionPerformed

    private void empresasCadastradasComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_empresasCadastradasComboBoxPropertyChange

    }//GEN-LAST:event_empresasCadastradasComboBoxPropertyChange
    
    private void preencherCampos(Empresa empresa) {
        cnpjEmpresaTextField.setText(String.valueOf(empresa.getCNPJ()));
        idEmpresaTextField.setText(String.valueOf(empresa.getId()));
        nomeEmpresaTextField.setText(empresa.getNome());
        enderecoEmpresaTextField.setText(empresa.getEndereco());
    }
    private void limparTextos (){
        idEmpresaTextField.setText("");
        cnpjEmpresaTextField.setText("");
        nomeEmpresaTextField.setText("");
        enderecoEmpresaTextField.setText("");
    }
    
    private void inicializarComboBoxEmpresa() {
        DefaultComboBoxModel<String> comboBoxEmpresasCadastradasModel = new DefaultComboBoxModel<>();

        // Obter as empresas cadastradas
        List<Empresa> empresas = controlador.listarEmpresas();

        // Preencher o modelo da lista com os nomes das empresas
        for (Empresa empresa : empresas) {
            comboBoxEmpresasCadastradasModel.addElement(empresa.getNomeECNPJ());
        }

        empresasCadastradasComboBox.setModel(comboBoxEmpresasCadastradasModel);
    }
    
    private void selecionarEmpresa(String empresaSelecionada) {
        String[] partes = empresaSelecionada.split(" - ");
        String nomeEmpresa = partes[0];
        String cnpjEmpresa = partes[1];

        cnpjEmpresaTextField.setText(cnpjEmpresa);
        Empresa empresa = controlador.buscarEmpresaPorCNPJ(cnpjEmpresa);
        this.preencherCampos(empresa);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastroEmpresas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarEmpresaButton;
    private javax.swing.JButton buscarEmpresaButton;
    private javax.swing.JButton cadastrarEmpresaButton;
    private javax.swing.JLabel cnpjEmpresaLabel;
    private javax.swing.JTextField cnpjEmpresaTextField;
    private javax.swing.JComboBox<String> empresasCadastradasComboBox;
    private javax.swing.JLabel empresasCadastradasLabel;
    private javax.swing.JLabel enderecoEmpresaLabel;
    private javax.swing.JTextField enderecoEmpresaTextField;
    private javax.swing.JLabel idEmpresaLabel;
    private javax.swing.JTextField idEmpresaTextField;
    private javax.swing.JButton limparCamposEmpresaButton;
    private javax.swing.JLabel nomeEmpresaLabel;
    private javax.swing.JTextField nomeEmpresaTextField;
    private javax.swing.JButton removerEmpresaButton;
    // End of variables declaration//GEN-END:variables
}
