/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controle.ControladorEmprego;
import controle.ControladorEmpresa;
import controle.ControladorFuncionário;
import javax.swing.JOptionPane;

import persistência.DB;
/**
 *
 * @author edmar
 */
public class JanelaRecursosHumanos extends javax.swing.JFrame {

    /**
     * Creates new form JanelaRecursosHumanos
     */
    public JanelaRecursosHumanos() {
        DB.criaConexão();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        janelaCadastroEmpresaMenuBar = new javax.swing.JMenu();
        cadastrarEmpresaMenuItem = new javax.swing.JMenuItem();
        janelaCadastroFuncionarioMenuBar = new javax.swing.JMenu();
        cadastrarFuncionarioMenuItem = new javax.swing.JMenuItem();
        janelaCadastroEmpregoMenuBar = new javax.swing.JMenu();
        cadastrarEmpregoMenuItem = new javax.swing.JMenuItem();
        pesquisarEmpregoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recursos Humanos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        janelaCadastroEmpresaMenuBar.setText("Empresas");
        janelaCadastroEmpresaMenuBar.setActionCommand("equipamentosMenuBar");
        janelaCadastroEmpresaMenuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                janelaCadastroEmpresaMenuBarActionPerformed(evt);
            }
        });

        cadastrarEmpresaMenuItem.setText("Cadastrar Empresa");
        cadastrarEmpresaMenuItem.setActionCommand("cadastrarEquipamentosMenuItem");
        cadastrarEmpresaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEmpresaMenuItemActionPerformed(evt);
            }
        });
        janelaCadastroEmpresaMenuBar.add(cadastrarEmpresaMenuItem);

        jMenuBar1.add(janelaCadastroEmpresaMenuBar);

        janelaCadastroFuncionarioMenuBar.setText("Funcionário");
        janelaCadastroFuncionarioMenuBar.setActionCommand("");
        janelaCadastroFuncionarioMenuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                janelaCadastroFuncionarioMenuBarActionPerformed(evt);
            }
        });

        cadastrarFuncionarioMenuItem.setText("Cadastrar Funcionário");
        cadastrarFuncionarioMenuItem.setActionCommand("cadastrarEmpregadoMenuItem");
        cadastrarFuncionarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionarioMenuItemActionPerformed(evt);
            }
        });
        janelaCadastroFuncionarioMenuBar.add(cadastrarFuncionarioMenuItem);

        jMenuBar1.add(janelaCadastroFuncionarioMenuBar);

        janelaCadastroEmpregoMenuBar.setText("Emprego");

        cadastrarEmpregoMenuItem.setText("Cadastrar Emprego");
        cadastrarEmpregoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEmpregoMenuItemActionPerformed(evt);
            }
        });
        janelaCadastroEmpregoMenuBar.add(cadastrarEmpregoMenuItem);

        pesquisarEmpregoMenuItem.setText("Pesquisar Emprego");
        janelaCadastroEmpregoMenuBar.add(pesquisarEmpregoMenuItem);

        jMenuBar1.add(janelaCadastroEmpregoMenuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void janelaCadastroEmpresaMenuBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_janelaCadastroEmpresaMenuBarActionPerformed
    }//GEN-LAST:event_janelaCadastroEmpresaMenuBarActionPerformed

    private void cadastrarEmpresaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEmpresaMenuItemActionPerformed
        new ControladorEmpresa();
    }//GEN-LAST:event_cadastrarEmpresaMenuItemActionPerformed

    private void janelaCadastroFuncionarioMenuBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_janelaCadastroFuncionarioMenuBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_janelaCadastroFuncionarioMenuBarActionPerformed

    private void cadastrarFuncionarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioMenuItemActionPerformed
        new ControladorFuncionário();
    }//GEN-LAST:event_cadastrarFuncionarioMenuItemActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        DB.fechaConexão();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void cadastrarEmpregoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEmpregoMenuItemActionPerformed
        new ControladorEmprego();
    }//GEN-LAST:event_cadastrarEmpregoMenuItemActionPerformed
    
    private void informarServiçoIndisponível(){
        JOptionPane.showMessageDialog (this, "Serviço Indisponivel", "Informação",
                JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaRecursosHumanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaRecursosHumanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaRecursosHumanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaRecursosHumanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaRecursosHumanos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarEmpregoMenuItem;
    private javax.swing.JMenuItem cadastrarEmpresaMenuItem;
    private javax.swing.JMenuItem cadastrarFuncionarioMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu janelaCadastroEmpregoMenuBar;
    private javax.swing.JMenu janelaCadastroEmpresaMenuBar;
    private javax.swing.JMenu janelaCadastroFuncionarioMenuBar;
    private javax.swing.JMenuItem pesquisarEmpregoMenuItem;
    // End of variables declaration//GEN-END:variables
}
