/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controle.ControladorEmprego;
import entidade.Emprego;
import entidade.Empresa;
import entidade.Funcionário;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author edmar
 */
public class JanelaCadastroEmprego extends javax.swing.JFrame {
    ControladorEmprego controlador;
    DefaultListModel<Emprego> listaEmpregos;
    Funcionário[] funcionariosCadastrados;
    Empresa[] empresasCadastradas;
    /**
     * Creates new form JanelaCadastroEmprego
     */
    public JanelaCadastroEmprego(ControladorEmprego controlador) {
        this.controlador = controlador;
        funcionariosCadastrados = Funcionário.getVisoes();
        empresasCadastradas = Empresa.getVisoes();
        initComponents();
        inicializarListaEmpregos();
        limparCampos();
    }
    private void atualizarListaEmpregos() {
        DefaultListModel<Emprego> novaListaEmpregos = new DefaultListModel<>();
        Emprego[] visões = Emprego.getVisoes(); // Obtém os empregos cadastrados do banco de dados

        for (Emprego visão : visões) {
            novaListaEmpregos.addElement(visão);
        }

        empregosCadastradosList.setModel(novaListaEmpregos);
    }
    private void limparCampos(){
        idEmpregoTextField.setText("");
        funcionariosCadastradosComboBox.setSelectedIndex(-1);
        empresasCadastradasComboBox.setSelectedIndex(-1);
        dataInicioTextField.setText("");
        dataDemissaoTextField.setText("");
    }
    private void informarErro(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Erro", JOptionPane.ERROR_MESSAGE);
    }
    private void inicializarListaEmpregos() {
        listaEmpregos = (DefaultListModel) empregosCadastradosList.getModel();
        Emprego[] visões = Emprego.getVisoes();
        for (Emprego visão : visões) {
            listaEmpregos.addElement(visão);
        }
    }
    private Funcionário getVisaoFuncionarioSelecionado(Emprego emprego) {
        for (Funcionário funcionario : funcionariosCadastrados) {
            if (emprego.getFuncionario().getId() == funcionario.getId()) {
                return funcionario;
            }
        }

        return null;
    }
    private Empresa getVisaoEmpresaSelecionada(Emprego emprego) {
        for (Empresa empresa : empresasCadastradas) {
            if (emprego.getEmpresa().getCNPJ().equals(empresa.getCNPJ())) {
                return empresa;
            }
        }

        return null;
    }
    public Timestamp transformarDataStringParaTimestamp(String dataStr){
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date data = dateFormat.parse(dataStr);
            return new Timestamp(data.getTime());
        } catch (ParseException e) {
            e.printStackTrace();
            return null;
        }
    }
    private Emprego obtemEmpregoInformado() {
        Funcionário visaoFuncionario = (Funcionário) funcionariosCadastradosComboBox.getSelectedItem();
        if (visaoFuncionario == null) {
            return null;
        }

        Empresa visaoEmpresa = (Empresa) empresasCadastradasComboBox.getSelectedItem();
        if (visaoEmpresa == null) {
            return null;
        }

        String idEmpregoStr = idEmpregoTextField.getText();
        int idEmprego = 0;
        if (!idEmpregoStr.isEmpty()) {
            idEmprego = Integer.parseInt(idEmpregoStr);
        }

        String dataInicioStr = dataInicioTextField.getText();
        Timestamp dataInicio = new Timestamp(Calendar.getInstance().getTimeInMillis());
        if (!dataInicioStr.isEmpty()) {
            dataInicio = transformarDataStringParaTimestamp(dataInicioStr);
        }

        String dataDemissaoStr = dataDemissaoTextField.getText();
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.YEAR, 200);
        Timestamp dataDemissao = new Timestamp(calendar.getTimeInMillis());
        if (!dataDemissaoStr.isEmpty()) {
            dataDemissao = transformarDataStringParaTimestamp(dataDemissaoStr);
        }

        return new Emprego(idEmprego, visaoFuncionario, visaoEmpresa, dataInicio, dataDemissao);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empregosCadastradosScrollPane = new javax.swing.JScrollPane();
        empregosCadastradosList = new javax.swing.JList();
        empregosCadastradosLabel = new javax.swing.JLabel();
        idEmpregoLabel = new javax.swing.JLabel();
        idEmpregoTextField = new javax.swing.JTextField();
        funcionariosCadastradosComboBox = new javax.swing.JComboBox();
        funcionariosCadastradosLabel = new javax.swing.JLabel();
        empresasCadastradasComboBox = new javax.swing.JComboBox();
        empresasCadastradasLabel = new javax.swing.JLabel();
        dataInicioCadastroLabel = new javax.swing.JLabel();
        dataInicioTextField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        cadastrarButton = new javax.swing.JButton();
        buscarButton = new javax.swing.JButton();
        alterarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        dataDemissaoTextField = new javax.swing.JTextField();
        data_hora_cadastroLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        empregosCadastradosList.setModel(new DefaultListModel());
        empregosCadastradosScrollPane.setViewportView(empregosCadastradosList);

        empregosCadastradosLabel.setText("Empregos Cadastrados");

        idEmpregoLabel.setText("ID do Emprego");

        idEmpregoTextField.setEditable(false);
        idEmpregoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEmpregoTextFieldActionPerformed(evt);
            }
        });

        funcionariosCadastradosComboBox.setModel(new DefaultComboBoxModel (funcionariosCadastrados));

        funcionariosCadastradosLabel.setText("Funcionários Cadastrados");

        empresasCadastradasComboBox.setModel(new DefaultComboBoxModel (empresasCadastradas));

        empresasCadastradasLabel.setText("Empresas Cadastradas");

        dataInicioCadastroLabel.setText("Data de admissão");

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButton(evt);
            }
        });
        buttonPanel.add(cadastrarButton);

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButton(evt);
            }
        });
        buttonPanel.add(buscarButton);

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarButton(evt);
            }
        });
        buttonPanel.add(alterarButton);

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButton(evt);
            }
        });
        buttonPanel.add(removerButton);

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButton(evt);
            }
        });
        buttonPanel.add(limparButton);

        data_hora_cadastroLabel.setText("Data demissão");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(empregosCadastradosLabel)
                .addGap(13, 13, 13)
                .addComponent(empregosCadastradosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(idEmpregoLabel)
                .addGap(12, 12, 12)
                .addComponent(idEmpregoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(funcionariosCadastradosLabel)
                .addGap(12, 12, 12)
                .addComponent(funcionariosCadastradosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(empresasCadastradasLabel)
                .addGap(12, 12, 12)
                .addComponent(empresasCadastradasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(dataInicioCadastroLabel)
                .addGap(12, 12, 12)
                .addComponent(dataInicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(data_hora_cadastroLabel)
                .addGap(12, 12, 12)
                .addComponent(dataDemissaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(empregosCadastradosLabel))
                    .addComponent(empregosCadastradosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(idEmpregoLabel))
                    .addComponent(idEmpregoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(funcionariosCadastradosLabel))
                    .addComponent(funcionariosCadastradosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(empresasCadastradasLabel))
                    .addComponent(empresasCadastradasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(dataInicioCadastroLabel))
                    .addComponent(dataInicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(data_hora_cadastroLabel))
                    .addComponent(dataDemissaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButton
        Emprego emprego = obtemEmpregoInformado();
        if (emprego != null) {
            String mensagemErro = controlador.inserirEmprego(emprego);
            if (mensagemErro == null) {
                int id = Emprego.ultimoId();
                emprego.setId(id);
                atualizarListaEmpregos();
                empregosCadastradosList.setSelectedIndex(listaEmpregos.size());
                limparCampos();
            } else {
                informarErro(mensagemErro);
            }
        }
    }//GEN-LAST:event_cadastrarButton

    private void buscarButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButton
        Emprego visao = (Emprego) empregosCadastradosList.getSelectedValue();
        if (visao != null) {
            Emprego emprego = Emprego.buscarEmprego(visao.getId());
            if (emprego != null) {
                idEmpregoTextField.setText("" + emprego.getId());
                dataInicioTextField.setText("" + emprego.getDataInicio());
                dataDemissaoTextField.setText("" + emprego.getDataFim());
                funcionariosCadastradosComboBox.setSelectedItem(getVisaoFuncionarioSelecionado(emprego));
                empresasCadastradasComboBox.setSelectedItem(getVisaoEmpresaSelecionada(emprego));
            } else {
                informarErro("Emprego não encontrado");
            }
        } else {
            informarErro("Nenhum Emprego selecionado");
        }   
    }//GEN-LAST:event_buscarButton

    private void alterarButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarButton
        Emprego emprego = obtemEmpregoInformado();
        String mensagemErro = null;

        if (emprego != null) {
            mensagemErro = controlador.alterarEmprego(emprego);
            atualizarListaEmpregos();
        } else {
            mensagemErro = "Algum atributo do emprego não foi informado";
        }

        if (mensagemErro != null) {
            informarErro(mensagemErro);
        }
    }//GEN-LAST:event_alterarButton

    private void removerButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButton
        Emprego visao = (Emprego) empregosCadastradosList.getSelectedValue();
        if (visao != null) {
            String mensagemErro = controlador.removerEmprego(visao.getId());
            if (mensagemErro == null) {
                atualizarListaEmpregos();
            } else {
                informarErro(mensagemErro);
            }
        } else {
            informarErro("Nenhum Emprego selecionado");
        }
    }//GEN-LAST:event_removerButton

    private void idEmpregoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEmpregoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEmpregoTextFieldActionPerformed

    private void limparButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButton
        limparCampos();
    }//GEN-LAST:event_limparButton



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField dataDemissaoTextField;
    private javax.swing.JLabel dataInicioCadastroLabel;
    private javax.swing.JTextField dataInicioTextField;
    private javax.swing.JLabel data_hora_cadastroLabel;
    private javax.swing.JLabel empregosCadastradosLabel;
    private javax.swing.JList empregosCadastradosList;
    private javax.swing.JScrollPane empregosCadastradosScrollPane;
    private javax.swing.JComboBox empresasCadastradasComboBox;
    private javax.swing.JLabel empresasCadastradasLabel;
    private javax.swing.JComboBox funcionariosCadastradosComboBox;
    private javax.swing.JLabel funcionariosCadastradosLabel;
    private javax.swing.JLabel idEmpregoLabel;
    private javax.swing.JTextField idEmpregoTextField;
    private javax.swing.JButton limparButton;
    private javax.swing.JButton removerButton;
    // End of variables declaration//GEN-END:variables
}
