/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

/**
 *
 * @author edmar
 */
public class PainelEstagiário extends javax.swing.JPanel {

    /**
     * Creates new form PainelEstagiario
     */
    public PainelEstagiário() {
        initComponents();
    }
    
    public String getCurso() {
        if(cursoTextField.getText().isEmpty())
            return null;
        
        return cursoTextField.getText();
    } 
    
    public Integer getCargaHoraria() {
        if(cargaHorariaTextField.getText().isEmpty())
            return null;
        
        return Integer.valueOf(cargaHorariaTextField.getText());
    }
    public void setCurso(String curso) {
        cursoTextField.setText(curso);
    }
    
    public void setCargaHoraria(Integer cargaHoraria) {
        cargaHorariaTextField.setText(cargaHoraria.toString());
    }
    
    public void limparTexto() {
        cargaHorariaTextField.setText("");
        cursoTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargaHorariaLabel = new javax.swing.JLabel();
        cargaHorariaTextField = new javax.swing.JTextField();
        cursoLabel = new javax.swing.JLabel();
        cursoTextField = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(376, 96));

        cargaHorariaLabel.setText("Carga Horaria:");

        cargaHorariaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cargaHorariaTextFieldKeyTyped(evt);
            }
        });

        cursoLabel.setText("Curso:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cursoLabel)
                    .addComponent(cargaHorariaLabel)
                    .addComponent(cursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargaHorariaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cursoLabel)
                .addGap(7, 7, 7)
                .addComponent(cursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cargaHorariaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargaHorariaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void cargaHorariaTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cargaHorariaTextFieldKeyTyped
        char caracteres = evt.getKeyChar();

        if(!Character.isDigit(caracteres)){
            evt.consume();
        }
    }//GEN-LAST:event_cargaHorariaTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cargaHorariaLabel;
    private javax.swing.JTextField cargaHorariaTextField;
    private javax.swing.JLabel cursoLabel;
    private javax.swing.JTextField cursoTextField;
    // End of variables declaration//GEN-END:variables
}
